### ISSUE TITLE
USER STORY: User comments on poll

### ISSUE THREAD

**Issue by leah-jala** [leah-jala/user-story-template#6]
As a **user**, I can **add comments to a poll** so that **can provide detailed feedback beyond the poll question**.

#3 

## Acceptance criteria:
1.  A comment box should be present under the poll.
2.  There should be a submit button.
3.  The user should receive a confirmation/thank you message.

## Tasks
- [ ] Use html and css to add a text box
- [ ] Add a character count
- [ ] Place a submit button under the text box.
- [ ] Generate user message
- [ ] Test functionality
