### ISSUE TITLE
USER STORY: Respond to a poll

### ISSUE THREAD

**Issue by leah-jala** [leah-jala/user-story-template#7]
As a **user**, I can **answer a poll** so that **I can give my opinion about a running event**.

** Acceptance Criteria**
1.  The results to date should be shown, including the number of responses.
2.  There should be a simple, single question.
3.  Users should rate their answer by clicking 1-5 stars

## Tasks
- [ ] Create a homepage message about the poll
- [ ] Create a button for the poll
- [ ] Create poll form
- [ ] Test functionality
